version: '3'

services:
  downpump:
    build: .
    container_name: downpump
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai