version: '3'

services:
  downpump:
    # 使用DockerHub镜像（取消注释并替换为你的DockerHub用户名）
    # image: 用户名/downpump:latest
    # 或使用本地构建
    build: .
    container_name: downpump
    volumes:
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai