services:
  downpump:
    image: aierliz/downpump:latest
    container_name: downpump
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml
    environment:
      - TZ=Asia/Shanghai